theme:
  name: material
site_name: Home Alarm
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Configuration:
    - Main Configuration: config/index.md
    - Alexa: config/alexa.md
    - Google Home & Others: config/others.md
  - Identification: identification.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true